// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	KV: KVNamespace;
	BETTER_AUTH_URL: string;
	BETTER_AUTH_SECRET: string;
	DB: D1Database;
	ASSETS: Fetcher;
}
